### PR TITLE
Mesa 22.0.0

### LINKED ISSUE #351: Mesa & kernel issue with Radeon 6500XT
Upgraded from 21.10.

There is a known issue https://gitlab.freedesktop.org/drm/amd/-/issues/1933

An upgrade to Mesa or downgrade to kernel should fix this issue.

### PR DESCRIPTION
**Pull request by jackpot51**
Should fix https://github.com/pop-os/beta/issues/351. If this only works on 22.04, we can only release it there. Requires https://github.com/pop-os/libdrm/pull/2 to be merged first

### CODE REVIEW

**Comment by XV-02** [comment]
When you indicate this "requires #7" it redirects to this PR. What did you mean by that comment? Is it a reference to https://github.com/pop-os/libdrm/pull/2 ?

**Comment by jackpot51** [comment]
@XV-02 yes, I meant to say https://github.com/pop-os/libdrm/pull/2 needs to be merged prior to this being able to build on all platforms

**Comment by XV-02** [comment]
# Testing
This document provides a guideline for testing and verifying MESA driver updates. Copy this checklist and mark items as they are verified to work.

These tests _must_ be performed on every OS version that the driver will be released on. Typically, that will be the Pop!\_OS regular release, the Pop!\_OS LTS, and the Ubuntu LTS.

## Installation

Add the staging branch containing the updated driver with the [apt script](https://github.com/pop-os/pop/blob/master/scripts/apt) in the pop-os/pop repo.

- [x] `sudo apt upgrade` updates the driver without conflicts (Ubuntu may require `full-upgrade`).

## Desktop graphics

Several graphics cards will have to be tested, preferably in several desktops. Test at least one current generation AMD card, as well as one previous generation AMD card. Additionally, test an Integrated AMD desktop and an Integrated Intel desktop.

- [x] HDMI-out (including sound output) works at expected resolution and refresh rate
- [x] DisplayPort-out (including sound output) works at expected resolution and refresh rate
- [x] Daisy-chained DisplayPort monitors (DP alt mode) work at expected resolution and refresh rate
- [x] Hot plugging/unplugging displays works as expected
- [x] Multiple displays at once work as expected

## Laptop graphics (switchable graphics)

Switchable graphics laptops can render with either the CPU-integrated GPU or the dedicated NVIDIA GPU. Before installing the driver update, make sure the machine is in Hybrid graphics mode.

- [x] After update and reboot, the machine remained in Hybrid graphics mode.

### Integrated mode/ Integrated only test

- [x] Plugging in a display correctly prompts to switch to Hybrid mode
- [x] Laptop suspends and resumes

### Hybrid mode tests

- [x] Laptop suspends and resumes
- [x] Both Nvidia and Integrated GPUs are correctly reported

## Software tests - Discrete AMD

- [x] A Unigine benchmark performs as expected
- [x] Steam can be installed and launched
    - [x] Steam can launch from the launcher
    - [x] Steam can launch from the terminal
- [x] A native Linux game can be launched from Steam
- [x] A Proton game can be launched from Steam

## Software tests - Integrated AMD

- [x] A Unigine benchmark performs as expected
- [x] Steam can be installed and launched
    - [x] Steam can launch from the launcher
    - [x] Steam can launch from the terminal
- [x] A native Linux game can be launched from Steam
- [x] A Proton game can be launched from Steam

## Software tests - Integrated Intel

- [x] A Unigine benchmark performs as expected
- [X] Steam can be installed and launched
    - [x] Steam can launch from the launcher
    - [X] Steam can launch from the terminal
- [x] A native Linux game can be launched from Steam
- [x] A Proton game can be launched from Steam

**Review by XV-02 — APPROVED** [review]
Nothing appears to be broken by this update, and it passed all the sanity checks I could reasonably think of. Also approving https://github.com/pop-os/libdrm/pull/2

**Review by XV-02 — CHANGES_REQUESTED** [review]
So, got a little trigger happy there. This either needs successful builds for Impish and Focal, or to be set for the Jammy release.

**Comment by jackpot51** [comment]
Closing, recommending to use Ubuntu 22.04 version on 22.04

**Pull request closed without merging**
