### PR TITLE
Mesa 22.3.4

### PR DESCRIPTION
**Pull request by 13r0ck**

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by leviport** [comment]
Looks like the A770 still doesn't work with this update and https://github.com/pop-os/linux/pull/214. Brock says it needs 6.2.

The 7900XT is also not working. Two different Miras get stuck on the BIOS boot splash when booting.

**Comment by mmstick** [comment]
I think AMD 7900XT just needs an update to our `linux-firmware` package.

**Comment by 13r0ck** [comment]
> I think AMD 7900XT just needs an update to our linux-firmware package.

On it!

**Comment by n3m0-22** [comment]
Testing with `Pop 22.04` on `lemp11`, `gaze15`, and `Dev One` passed. Holding off on approval till `AMD/NVIDIA`, `Discrete AMD` and `daisy-chain` as well as `Ubuntu` testing is complete.

[mesa-22.3.4-testing.txt](https://github.com/pop-os/mesa/files/10574444/mesa-22.3.4-testing.txt)

**Comment by leviport** [comment]
DP MST still works on Dev One with this PR.

**Comment by n3m0-22** [comment]
Testing has passed for `Ubuntu 22.04` on the `lemp11`, `Dev One`, and mostly on the `gaze15`. On an NVIDIA system the 525 driver in `master` is needed.

This leads to a problem as some of the other packages in master are causing issues in Ubuntu. I'm in the process of tracking down the specific packages and the issues they are causing.

I will leave more details here as they come in, and link to any related issues as they are identified.

**Comment by XV-02** [comment]
# Testing MESA 22.3.4 Pop 22.04 Discrete AMD (RX580)

## Installation

Add the staging branch containing the updated driver with the [apt script](https://github.com/pop-os/pop/blob/master/scripts/apt) in the pop-os/pop repo.

- [x] `sudo apt upgrade` updates the driver without conflicts (Ubuntu may require `full-upgrade`).

## Desktop graphics

Several graphics cards will have to be tested, preferably in several desktops. Test at least one current generation AMD card, as well as one previous generation AMD card.

- [x] HDMI-out (including sound output) works at expected resolution and refresh rate
- [X] DisplayPort-out (including sound output) works at expected resolution and refresh rate
- [x] Daisy-chained DisplayPort monitors (DP alt mode) work at expected resolution and refresh rate
- [X] Hot plugging/unplugging displays works as expected
- [x] Multiple displays at once work as expected

## Software tests

These can be done on any machine with an NVIDIA GPU

- [x] A Unigine benchmark performs as expected
- [x] Steam can be installed and launched
- [x] A native Linux game can be launched from Steam
- [x] A Proton game can be launched from Steam

**Review by n3m0-22 — APPROVED** [review]
All previously mentioned issues with Ubuntu 22.04 on an NVIDIA laptop have been resolved. All other testing is still passing. This looks good to go now.

**Comment by 13r0ck** [comment]
@pop-os/quality-assurance  Did we confirm https://github.com/pop-os/linux-firmware/pull/28 fixes the amd rx 7000 GPUs?

**Comment by leviport** [comment]
Not for certain yet.

**Comment by leviport** [comment]
The RX 7900XT is fixed with this and https://github.com/pop-os/linux-firmware/pull/28, but there is an xorg bug that makes the mouse cursor disappear. More details can be found in https://github.com/pop-os/linux-firmware/pull/28

Still, no mouse cursor is much better than no booting. I think we are good to release this and https://github.com/pop-os/linux-firmware/pull/28, then try to address the xorg mouse cursor bug before we begin selling the cards in the Thelio line.

**Review by leviport — APPROVED** [review]

**Pull request merged**
