### PR TITLE
Mesa 23.3.0

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by leviport** [comment]
This is looking great on Pop, but I think Ubuntu still needs wayland-protocols. I'm not seeing it in the release script, so it might need to be manually added to launchpad or something.

**Comment by leviport** [comment]
Any news on fixing this in Ubuntu? Thomas reports significant performance gains on serw13 in Integrated mode with this update, and Ubuntu is the only thing blocking it at this point.

**Comment by mmstick** [comment]
We could release it here and push to Ubuntu after.

**Comment by mmstick** [comment]
It's been a while since I've pushed something to Launchpad. I'll look into pushing the wayland-protocols package there soon.

**Review by leviport — APPROVED** [review]
Approving for Pop release, and we can sort out the Ubuntu release later down the line then.

**Comment by mmstick** [comment]
https://launchpad.net/~system76-dev/+archive/ubuntu/pre-stable/+build/27191665 This is building. If we can verify it and get it in the release repo, I'll merge this so it gets building on Ubuntu

**Comment by leviport** [comment]
Awesome, sounds good

**Comment by mmstick** [comment]
I pushed a change to have it build for i386 as well: https://launchpad.net/~system76-dev/+archive/ubuntu/pre-stable/+builds

**Comment by pojunen** [comment]
Mesa 23.3.1 (regression fixes from first 23.3.x release)
https://docs.mesa3d.org/relnotes/23.3.1.html

https://salsa.debian.org/xorg-team/lib/mesa/-/commit/7a91174d49c1e1656e235727e26cc3f24ca31a5b

**Comment by mmstick** [comment]
@pop-os/quality-assurance OK to push wayland-protocols to the Ubuntu release repo?

**Comment by leviport** [comment]
> @pop-os/quality-assurance OK to push wayland-protocols to the Ubuntu release repo?

Yep, should be good to go

**Pull request merged**
