### PR TITLE
Mesa 23.3.0~rc5

### PR DESCRIPTION
**Pull request by mmstick**
This is for the purpose of testing for a possible fix for an AMD Radeon card with Steam. Unfortunately, we can't test LLVM 17 since Ubuntu 22.04 only provides LLVM 15 at this time.

Requires https://github.com/pop-os/wayland-protocols/pull/1

### CODE REVIEW

**Comment by mmstick** [comment]
This can now be tested on Pop!_OS, though for Ubuntu we'll need the wayland-protocols package released there.

**Comment by leviport** [comment]
I'll release that on Ubuntu now

**Comment by mmstick** [comment]
Since this is a release candidate, we can hold off on releasing this until Mesa has an official release. But it'd be nice to know if this fixes our Steam issue. If not linux-firmware or the Linux kernel, then it must be a Mesa/GNOME issue.

I notice we never released GNOME 42.9 packaging that we tested earlier.

**Comment by leviport** [comment]
This also does not resolve the Steam + RX 7600 bug.

**Pull request closed without merging**
