### PR TITLE
Mesa 22.3.0-3

### PR DESCRIPTION
**Pull request by 13r0ck**

### CODE REVIEW

**Comment by mmstick** [comment]
Looks like we need to backport `https://packages.ubuntu.com/lunar/llvm-spirv-15` to get the missing `llvm-spirv-15` dependencies.

**Comment by mmstick** [comment]
This should work https://salsa.debian.org/opencl-team/spirv-llvm-translator/-/tree/llvm15/main

**Comment by 13r0ck** [comment]
Ya thats what I was thinking, If you think thats a good idea, then I will do it

**Comment by kostadinsh** [comment]
Note: If you don't know already, all of llvm 15 might be needed if you want to enable support for RDNA3/gfx11.

See also: https://bbs.archlinux.org/viewtopic.php?id=282114
https://www.reddit.com/r/archlinux/comments/zn8fhb/comment/j0gljn1/?context=3

**Comment by 13r0ck** [comment]
closed in favor of #11

**Comment by jackpot51** [comment]
Force pushed after `git commit --amend` to force a rebuild

**Review by jackpot51 — APPROVED** [review]

**Comment by mmstick** [comment]
We should get [22.3.4](https://salsa.debian.org/xorg-team/lib/mesa/-/commits/mesa-22.3.4-1/) packaged if possible. Mesa's about to switch to 22.4.0 soon so this has their latest fixes for this release.

**Comment by 13r0ck** [comment]
PR tag, #13  is it now

**Pull request closed without merging**
